import "package:get/get.dart";

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        "tr_TR": {
          "signup": "Kayıt Ol",
          "login": "Giriş Yap",
          "empty_error": "Lütfen bir değer giriniz",
          "password": "Password",
          "enter_password": "Lütfen şifrenizi giriniz",
          "email": "Email",
          "enter_email": "Lütfen emalinizi giriniz",
          "phone": "Telefon",
          "enter_phone": "Lütfen telefonunuzu giriniz",
          "error_phone": "Lütfen telefonunuzu giriniz",
          "search": "Ara ..",
          "search_hint": "Ülke isimlerini yazabilirsin",
          "login_error": "Girdiğiniz değerler yanlış",
          "city": "Şehir",
          "enter_city": "Lütfen şehrinizi giriniz",
          "company": "Firma",
          "enter_company": "Lütfen firma adını giriniz",
          "continue": "Devam",
          "first_name": "İsim",
          "enter_first_name": "Lütfen isminizi giriniz",
          "last_name": "Soy İsim",
          "enter_last_name": "Lütfen soy isminizi giriniz",
          "back": "Geri",
          "currency": "Para Birimi",
          "congratulations": "Tebrikler",
          "your_registration_has_been_successfully_completed":
              "Kaydınız başarıyla tamamlandı",
          "something_wrong_please_try_again":
              "Bir şeyle ters gitti Lütfen tekrar deneyin!",
          "shading_systems": "Gölgelendirme Sistemleri",
          "giosan_systems": "Giosan Cam Sistemleri",
          "logout": "Oturumu Kapat",
          "contact": "iletişim",
          "giosan_catalog": "Giosan Katalog",
          "persan_catalog": "Persan Katalog",
          "getprice": "Fiyat Al",
          "width": "Genişlik (Metre)",
          "width2": "Açılım (Metre)",
          "fabric": "Kumaş",
          "checkyourcredentials": "Bilgilerinizi kontrol ediniz",
          "price": "Fiyat",
          "fillrequiredfields": "Lütfen boş alanları doldurunuz"
        },
        "en_US": {
          "signup": "Sign Up",
          "login": "Login",
          "empty_error": "Please fill in the blanks",
          "password": "Password",
          "enter_password": "Please enter password",
          "email": "Email",
          "enter_email": "Please enter email",
          "phone": "Phone Number",
          "enter_phone": "Please enter phone number",
          "error_phone": "Please enter phone number",
          "search": "Search ..",
          "search_hint": "Start typing to search",
          "login_error": "The values you entered are incorrect",
          "city": "City",
          "enter_city": "Please enter your city",
          "company": "Company",
          "enter_company": "Please enter your company name",
          "continue": "Continue",
          "first_name": "First Name",
          "enter_first_name": "Please enter your First Name",
          "last_name": "Last Name",
          "enter_last_name": "Please enter your Last Name",
          "back": "Back",
          "currency": "Currency",
          "congratulations": "Congratulations",
          "your_registration_has_been_successfully_completed":
              "Your registration has been successfully completed",
          "something_wrong_please_try_again":
              "Something is wrong please try again",
          "shading_systems": "Shading Systems",
          "giosan_systems": "Giosan Systems",
          "logout": "Logout",
          "contact": "Contact",
          "giosan_catalog": "Giosan Catalog",
          "persan_catalog": "Persan Catalog",
          "getprice": "Get Price",
          "width": "Width (Meter)",
          "width2": "Forward Opening (Metre)",
          "fabric": "Fabric",
          "checkyourcredentials": "Check your credentials",
          "price": "Price",
          "fillrequiredfields": "Fill required fields"
        },
      };
}
